
from datetime import datetime
from consts import REPORT_VERSION, __git_hash__
from closure_helper import compute_dd_from_dms,compute_direct,compute_dms_from_dd,compute_dxdy_from_curve_delta,compute_dxdy_from_straightline
import math


def write_report_to_file(file_path,report_name,closure_information,direct_points):
    f = open(file_path,"w")
    f.write("Closure Report for %s\n"%report_name)
    f.write("Closure: 1/%.0f\n"%closure_information["closure"])
    f.write("Sum of distances of lines: %.3f\n"%closure_information["distance"])
    f.write("Displacement of final point: %.3f\n"%closure_information["displacement"])
    f.write("Coordinates of final point: (%.3f,%.3f)\n"%(closure_information["x"],closure_information["y"]))
    f.write("Date of report: %s\n"%datetime.today().strftime('%Y-%m-%d'))
    seg_count = 1
    for i in direct_points:
        if i['is_curve']:
            curve = i['curve_segment']
            f.write("\nCurve Segment %i:\n"%seg_count)
            f.write("Radius of Curve Segment: %.3f\n"%curve["radius"])
            f.write("Length of Curve Segment: %.3f\n"%curve["arc"])
            (d,m,s) = compute_dms_from_dd(abs(math.degrees(curve["arc"]/curve["radius"])))
            f.write("Delta of Curve Segment: %.0f-%.0f-%.3f\n"%(d,m,s))
            if curve["rad-bear"]:
                f.write("Radial Bearing of Curve Segment: %.0f-%.0f-%.3f\n"%(curve["rad-d"],curve["rad-m"],curve["rad-s"]))
            f.write("Bearing after Curve Segment: %.0f-%.0f-%.3f\n"%(curve["bearing-d"],curve["bearing-m"],curve["bearing-s"]))
        else:
            line = i['line_segment']
            f.write("\nLine Segment %i:\n"%seg_count)
            f.write("Distance of Line Segment: %.3f\n"%line["distance"])
            f.write("Bearing of Line Segment: %.0f-%.0f-%.3f\n"%(line["bearing-d"],line["bearing-m"],line["bearing-s"]))
        f.write("Coordinates of point after segment: (%f,%f)\n"%(i['y'],i['x']))
        seg_count+=1
    f.write("\n---Report Version %i---"%REPORT_VERSION)
    f.write("\n---Generated by closure-calc-gui version %s---"%__git_hash__)
    f.close()
    print(f"Data saved to {file_path}")